name: Daily Diary Summary

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日9:00 JST（UTC 0:00）
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai dropbox

      - name: Debug current directory
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -la

      - name: Run summarizer
        run: python 20250729_diary-summary-bot/summarize.py
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_TO: ${{ secrets.GMAIL_TO }}
